from distutils.core import setup, Extension
import os, sys

setup(name="flud",
		version="0.0.2", 
		description="flud decentralized backup", 
		long_description='a 100% decentralized backup system',
		author="Alen Peacock",
		author_email="apeacock@flud.org",
		url='http://flud.org',
		copyright='(c)2004-2007 Alen Peacock',
		license='GPL v3',
		packages=['flud', 
			'flud.protocol', 
			'flud.bin', 
			'flud.test',
			'flud.zfec',
			'flud.zfec.util'],
		package_dir={'flud': 'flud', 
			'flud.protocol': 'flud/protocol',
			'flud.bin': 'flud/bin',
			'flud.test': 'flud/test',
			'flud.zfec': 'flud/zfec',
			'flud.zfec.util': 'flud/zfec/util'},
		package_data={'flud': ['images/*.png', 'FludNode.tac']},
		scripts = ['flud/bin/fludnode',
			'flud/bin/tacpath-flud',
			'flud/bin/fludscheduler', 
			'flud/bin/fludclient', 
			'flud/bin/fludlocalclient',
			'flud/bin/flud-mastermetadataViewer',
			'flud/bin/flud-metadataViewer',
			'flud/bin/start-fludnodes', 
			'flud/bin/stop-fludnodes', 
			'flud/bin/gauges-fludnodes',
			'flud/bin/clean-fludnodes'],
		ext_modules=[Extension('_fec', 
			['flud/zfec/fec.c', 'flud/zfec/_fecmodule.c',], 
			extra_link_args=[], 
			extra_compile_args=['-std=c99'], 
			undef_macros=[])]
)


